version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.4
    container_name: nasij-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/sql

  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: nasij-tileserv
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on: [db]
    ports: ["7800:7800"]

  api:
    build: ../services/api
    container_name: nasij-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on: [db]
    ports: ["8088:8088"]

  web:
    build: ../apps/web
    container_name: nasij-web
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8088
    depends_on: [api]
    ports: ["3000:3000"]

  etl:
    build: ../services/etl
    container_name: nasij-etl
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on: [db]
    ports: ["9101:9101"]

  prometheus:
    image: prom/prometheus:latest
    container_name: nasij-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.1.0
    container_name: nasij-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports: ["3001:3000"]

  osrm:
    image: peterevans/osrm-backend:latest
    container_name: nasij-osrm
    environment:
      OSRM_PBF_URL: ${OSRM_PBF_URL}
    ports: ["5000:5000"]

volumes:
  db_data:
